
        
name : test pr
on:
   pull_request:
      branches:
         - master

jobs:
  build:
    runs-on: windows-2019 
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: dev.txt
