
        
name : test pr
on:
   pull_request:
      types: [locked, synchronize, reopened, edited, review_requested, review_request_removed, opened, ready_for_review]
      branches:
         - master

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: output event name
      run:  echo ${{github.event_name}}
    #- uses: actions/upload-artifact@master
      #with:
        #name: my-artifact
        #path: dev.txt
