name : checkout branch
on: push

jobs:
  job1:
    runs-on: ubuntu-16.04
    env: 
       working-directory: ./dir1

    steps:

    - uses: actions/checkout@master
    - name: dir2 directory
      run: ls -R 
    - name: dir1 directory
      run: |
          ls -R
          echo $working-directory 
      working-directory: ${{working-directory}}
  

      
