name : checkout branch
on: push

jobs:
  job1:
    runs-on: ubuntu-16.04
    env: 
       working-directory: ./dir1

    steps:

    - uses: actions/checkout@master
    - name: Clean temp directory
      run: rm -rf *
      working-directory: ./dir1
  

      
