name : use same working directory
on: 
 issues:
   types: [edited]

jobs:
  job1:
    runs-on: ubuntu-16.04
    env: 
       working-directory: ./dir1

    steps:

    - uses: actions/checkout@master
    - name: dir2 directory
      run: ls -R 
      working-directory: ${{env.working-directory}}
    - name: dir1 directory
      run: |
          ls -R
      working-directory: ${{env.working-directory}}
  

      
