name : test different path on PR trigger 
on: 
  pull_request:
    paths:
      - 'dir1/**'
      - '!dir2/**'

jobs:
  job1:
    runs-on: ubuntu-16.04

    steps:

    - uses: actions/checkout@v1

      
