name: broken_ci
on:
  - push
jobs:
  example:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v1
    - name: forked job
      run: |
        ls 
        cd dir1
        ls
    - name: this is never reached
      run: ls
