name: CI

on: 
  
  repository_dispatch:
    types: build
    

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        Write-Host Building Game using UE4 in ${env.UNREAL_DIRECTORY}
        Write-Host Building in ${env:GITHUB_WORKSPACE}
        mkdir ${env:GITHUB_WORKSPACE}\dist\
        mkdir ${env:GITHUB_WORKSPACE}\Build\
      
      env:
        UNREAL_DIRECTORY: 'C:\Program Files\Epic Games\UE_4.24'
    - name: Upload math result for job 2
      uses: actions/upload-artifact@v1
      with:
        name: Build
        path: ${{github.workspace}}\Build
      
