
name : push with tag and path

on:
  push:
    paths:
    - 'dir1/**'
    #tags:
   #- 'release-*'


jobs:
  job1:
    runs-on: ubuntu-16.04
    env: 
       working-directory: ./dir1
    steps:
    - uses: actions/checkout@master
