
name : push with tag 

on: check_run
  


jobs:
  job1:
    runs-on: ubuntu-16.04
    env: 
       working-directory: ./dir1
    steps:
    - uses: actions/checkout@master
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
       # Artifact name
        name: drop1
        # Directory containing files to upload
        path: dir1
