
name : matrix build

on:
  check_suite:


jobs:
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
     
    steps:
    - uses: actions/checkout@master
    - run : echo $REF
      env: 
        REF: ${{ github.ref }}
    - run: echo hello
      if: startsWith( github.ref, 'refs/heads/release-' )
      
