
name : push with path amd tag

on:
  check_suite:


jobs:
  job1:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
    - run: echo hello
      if: startsWith( github.ref, 'release-' )
      
