
name : push with path amd tag

on:
  push:


jobs:
  job1:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
    - run : echo $REF
      env: 
        REF: ${{ github.ref }}
    - run: echo hello
      if: startsWith( github.ref, 'refs/heads/release-' )
      
