name: CI

on: 
  push:
  repository_dispatch:
    types: build
    

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        Write-Host Building Game using UE4 in $UNREAL_DIRECTORY
        Write-Host Building in ${env:GITHUB_WORKSPACE}
        mkdir ${env:GITHUB_WORKSPACE}\dist\
        mkdir ${env:GITHUB_WORKSPACE}\Build\
        "$UNREAL_DIRECTORY\Engine\Binaries\DotNET\UnrealBuildTool.exe" -projectfiles -project="${env:GITHUB_WORKSPACE}\Landieval.uproject" -game -rocket -progress
        "$UNREAL_DIRECTORY\Engine\Binaries\DotNET\UnrealBuildTool.exe" Landieval Development Win64 -project="${env:GITHUB_WORKSPACE}\Landieval.uproject" -rocket -editorrecompile -progress -noubtmakefiles -NoHotReloadFromIDE -2017
        "$UNREAL_DIRECTORY\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -project="${env:GITHUB_WORKSPACE}\Landieval.uproject" -noP4 -platform=Win64 -clientconfig="Development" -cook -allmaps -build -stage -pak -archive -archivedirectory="${env:GITHUB_WORKSPACE}\dist\"
        Compress-Archive -Path "${env:GITHUB_WORKSPACE}\dist\" -DestinationPath "${env:GITHUB_WORKSPACE}\Build\Build.zip"
      env:
        UNREAL_DIRECTORY: 'C:\Program Files\Epic Games\UE_4.24'
    - name: Upload math result for job 2
      uses: actions/upload-artifact@v1
      with:
        name: Build
        path: $GITHUB_WORKSPACE/Build/Build.zip
      
