
name : push with tag 

on: push
  


jobs:
  job1:
    runs-on: windows-latest
    env: 
       working-directory: ./dir1
    steps:
    - uses: actions/checkout@master
    - run:
         Write-Host Building Game using UE4 in ${env:UNREAL_DIRECTORY}
      env:
        UNREAL_DIRECTORY: 'C:\Program Files\Epic Games\UE_4.24'
      shell: powershell
