name: broken_ci
on:
  - push
jobs:
  example:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v1
    - name: forked job
      run: |
        apt update && apt install -y iputils-ping
        ping google.ca > /tmp/ping.out &
        echo "this will echo"
    - name: this is never reached
      run: echo "i dont get echoed ever"
