name: broken_ci
on:
  - push
jobs:
  example:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: forked job
      run: |
        sudo apt-get update && sudo apt-get install -y iputils-ping
        ping google.ca 
        echo "this will echo"

    - name: this is never reached
      run: echo "i dont get echoed ever"
