
name : push with path

on:
  push:
    branches: 
      - master
    paths:
      - 'dir1/**'
    tags:

      - 'release-*'

jobs:
  job1:
    runs-on: ubuntu-16.04
    env: 
       working-directory: ./dir1
    steps:
    - uses: actions/checkout@master
