
name : push with tag 

on:
  push:
    tags:
      - 'release-*'
  


jobs:
  job1:
    runs-on: ubuntu-16.04
    env: 
       working-directory: ./dir1
    steps:
    - uses: actions/checkout@master
