name: download release asset
on:
  release:
    types: [published]

jobs:
  asset_fetcher:
    runs-on: ubuntu-latest
    steps:
    - run: echo $Release
      env: 
        Release: ${{ github.event.release }} 
    - uses: wyozi/download-gh-release-asset@master
      with: 
        args: yan-jing-zhu-2.5.zip
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
