name: download release asset
on:
  release:
    types: [published]

jobs:
  asset_fetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: wyozi/download-gh-release-asset@master
      with: 
        args: source code
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
